# Generated by Django 5.2 on 2026-08-25.
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)), ("title", models.CharField(max_length=120)),
                ("summary", models.TextField()), ("content", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(unique=True)),
                ("status", models.CharField(choices=[("draft", "草稿"), ("published", "已发布")], default="draft", max_length=16)),
            ], options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)), ("title", models.CharField(max_length=160)),
                ("provenance", models.TextField()), ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("draft", "草稿"), ("published", "已发布")], default="draft", max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("algorithm", models.CharField(max_length=100)), ("graph", models.JSONField()),
                ("parameters", models.JSONField(default=dict)), ("seed", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "等待中"), ("completed", "已完成"), ("failed", "失败")], default="pending", max_length=16)),
                ("result", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)), ("title", models.CharField(max_length=160)),
                ("summary", models.TextField()), ("content", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "草稿"), ("published", "已发布")], default="draft", max_length=16)),
                ("dataset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cases", to="learning.dataset")),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cases", to="learning.coursemodule")),
            ],
        ),
    ]
